In [12]:
#1
import numpy as np
a=[[1,2,3],[4,5,6]]
b=[[1,2,3],[4,5,6]]
a1=np.array(a)
b1=np.array(b)
print("1st metrice\n",a1)
print("2nd metrice\n",b1)
a1+b1

1st metrice
 [[1 2 3]
 [4 5 6]]
2nd metrice
 [[1 2 3]
 [4 5 6]]


array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [15]:
#2
a1=np.array(a)
b1=np.array(b)
print("1st metrice\n",a1)
print("2nd metrice\n",b1)
a1*b1

1st metrice
 [[1 2 3]
 [4 5 6]]
2nd metrice
 [[1 2 3]
 [4 5 6]]


array([[ 1,  4,  9],
       [16, 25, 36]])

In [37]:
#3
a2=np.transpose(a1)
print("Transposed value is\n",a2)

Transposed value is
 [[1 4]
 [2 5]
 [3 6]]


In [38]:
#4

s=['a','b','e','y','d','c','w','i','o','a']
s.sort()
print("Sorted value is \n",s)

Sorted value is 
 ['a', 'a', 'b', 'c', 'd', 'e', 'i', 'o', 'w', 'y']


In [55]:
#5

a=input("Enter the string ")
p='''''!()-[]{};:'"\,<>./?@#$%^&*_~'''
a1=""
for i in a:
    if i not in p:
        a1=a1+i
a1

Enter the string asddsa@dsfsd!./;'[]ppooo


'asddsadsfsdppooo'